# Generated by Django 6.0.3 on 2026-03-24 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_confirmed', models.BooleanField(default=True)),
                ('confirmate_token', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('token_expires', models.DateTimeField(blank=True, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True)),
                ('token_type', models.CharField(choices=[('activateion', 'Активация аккаунта'), ('change_email', 'Сиена email')], default='activation', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
