# Generated by Django 5.1.2 on 2025-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=786578, max_length=50),
            preserve_default=False,
        ),
    ]
