# Generated by Django 5.1.2 on 2025-10-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        ('wallet_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_account.user'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet_account.user'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='wallet_transact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
