# Generated by Django 5.1.2 on 2025-10-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=786578, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=786578, max_length=50),
            preserve_default=False,
        ),
    ]
